spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: false
    validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
security:
  app:
    jwtSecret: secretKey
    jwtExpirationMs: 86400000
jwt:
  secret : javainuse